version: '3.7'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb2'
    volumes:
      - ~/mongo_data3:/data/db
    environment:
      - MONGO_INITDB_DATABASE=catalogo
      - MONGO_INITDB_ROOT_USERNAME=catalogo
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017